### ISSUE TITLE
Layout background image / Question

### ISSUE THREAD

**Issue by adalidortiz** [sagiadinos/garlic-player#18]
Garlic Player support layout background image? Any help about it?

Saludos .

**Comment by sagiadinos** [comment]
Holá,

There is no support for background, currently. One possible workaround is: you can try to use two overlapping regions and set the "background" image in the back region as infinity loop.

I implement backgroundImage and backgroundRepeat functionality for regions yesterday,  but the solution is unsatisfying.

The problem is that QWidget supports only local files as backgrounds. So background image must downloaded first. If the player starts the SMIL-File with a remote background image for the first time, the download is not completed and background will not shown. 

Give me some time to find a more elegant solution. If you can live with local background files I can commit the current code.

**Comment by adalidortiz** [comment]
I'am wil try with overlays as you say.

Gracias !

**Comment by sagiadinos** [comment]
I changed some internal calls in the lib and now garlic-player (build v0.3.0.430) support background images and background-repeat attribute as expected. 
The workaround with a multi zone is not necessary anymore ;)

**Comment by adalidortiz** [comment]
Hi Mr. Sagiadinos, thanks for the feature. How can i include this feature in my smil index. Can you share the tags?

Gracias !!!

**Comment by sagiadinos** [comment]
Hi,
Here you can find a demonstration.

https://github.com/sagiadinos/garlic-player/blob/master/tests/data/smil/simple_par_with_backgrounds.smil

**Comment by adalidortiz** [comment]
Many thanks !!!
