### ISSUE TITLE
Compile instructions for Ubuntu and MacOS

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#23]
Hi -- would it be possible to update and/or create the build instructions (when starting from scratch) for Ubuntu and MacOS? 

Thanks
J

**Comment by sagiadinos** [comment]
You will find build instructions for Ubuntu 18.04 and Debian 10 in the [wiki](https://github.com/sagiadinos/garlic-player/wiki/HowTo-Build-with-Debian-10-(Buster)-and-Ubuntu-18.04)
It also works on Raspberry Pi OS 64Bit.

General compile iorder aere are:

1. Build QtAV /([instructions](https://github.com/wang-bin/QtAV/wiki/Build-QtAV))
2. Build zip from ./ext-dir
3. Build quazip from ./ext-dir
4. Build garlic-lib
5. Build widget-player (windows, macos, linux) or c2qml for Android and iOS. Should also work on webOS, but not tested.

I recommend QtAV instead of vlc-lib for Windows and macOS.

**Comment by jf133** [comment]
Thank you
