### ISSUE TITLE
update chromium

### ISSUE THREAD

**Issue by jf133** [sagiadinos/garlic-player#25]
Hi -- would it be possible to update chromium? Sites are complaining it's outdated. Example: bloomberg.com. Looks like garlic player is using 69.0.3497.128 which is from Oct 2018

Thank you!

**Comment by sagiadinos** [comment]
The reason is, that the binaries compile against Qt 5.12.11. They use a Chromium-Engine 69, but with a lot of back port patches. 
Maybe a change of the user agent could fool the Bloomberg site. I will check this. 

Another option is to compile against a newer Qt version like 5.13, 5.14 or 5.15 But to be honest: The stability of the 5.12  is incredible. Unfortunately, it is the last version with free LTS.
I am uncertain if it is possible to update QtWebengine separetely.

**Comment by jf133** [comment]
Hi Niko -- changing user agent won't help enabling features since 2018 that have been built in to chrome. I.e. autoplay for videos. streaming, etc.  So curious what chromium versions are contained in 5.15 and if they can be implemented. Definitely curious if just QtWebengine can be built separately. Thank you for your help!

**Comment by sagiadinos** [comment]
I understand.

Qt 5.12 Chromium 69
Qt 5.13 Chromium 73
Qt 5.14 Chromium 77
Qt 5.15 Chromium 80

Do not use Qt6 as they removed QXmlPatterns which is needed for conditional play:

So maybe a build with a higher Qt Version could solve your problem.
May I ask which OS you use?

The garlic-player android use the default webview from Android OS.

**Comment by jf133** [comment]
Hi -- thank you for checking. I'm using macos build now to test if I can use garlic-player (running on M1).  Would you be able to include instructions on how to incorporate different Qt builds to test if chromium will work? 

Even bigger favor would be to compile garlic with the Qt versions you mentioned above to test it out faster. Both would be greatly appreciated!

JF
